spring:
  application:
    name: sample-ecommerce

  jpa:
    show-sql: true
    format-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use-new-id-generator-mappings: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ecommerce
    password: root
    database:
      driverClassName: org.postgresql.jdbc.Driver

  flyway:
    locations: classpath:db/migration
    Schemas: ecommerce
    baselineOnMigrate: true
    url: jdbc:postgresql://localhost:5432/ecommerce
    user: ecommerce
    password: root

app:
  security:
    jwt:
      keystore-location: jwt-keystore.jks
      keystore-password: sampleecommerce
      key-alias: jwt-sign-key
      private-key-passphrase: sampleecommerce

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
