package com.jra.sampleecommerce.hateoas;

import com.jra.sampleecommerce.api.model.ShipmentDTO;
import com.jra.sampleecommerce.controller.ShipmentController;
import com.jra.sampleecommerce.model.entity.Shipment;
import org.springframework.beans.BeanUtils;
import org.springframework.hateoas.server.mvc.RepresentationModelAssemblerSupport;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Objects;
import java.util.stream.StreamSupport;

import static java.util.stream.Collectors.toList;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;

/**
 * @author : github.com/sharmasourabh
 * @project : Chapter04 - Modern API Development with Spring and Spring Boot Ed 2
 **/
@Component
public class ShipmentRepresentationModelAssembler extends RepresentationModelAssemblerSupport<Shipment, ShipmentDTO> {

  /**
   * Creates a new {@link RepresentationModelAssemblerSupport} using the given controller class and
   * resource type.
   */
  public ShipmentRepresentationModelAssembler() {
    super(Shipment.class, ShipmentDTO.class);
  }

  /**
   * Coverts the Shipment entity to resource
   * @param entity
   * @return
   */
  @Override
  public ShipmentDTO toModel(Shipment entity) {
    ShipmentDTO resource = createModelWithId(entity.getId(), entity);
    BeanUtils.copyProperties(entity, resource);
    resource.setId(entity.getId().toString());
    // Self link generated by createModelWithId has missing api path. Therefore, generating additionally.
    // can be removed once fixed.
    resource.add(linkTo(methodOn(ShipmentController.class).getShipmentByOrderId(entity.getId().toString())).withRel("byOrderId"));
    return resource;
  }

  /**
   * Coverts the collection of Product entities to list of resources.
   * @param entities
   * @return
   */
  public List<ShipmentDTO> toListModel(Iterable<Shipment> entities) {
    if (Objects.isNull(entities)) return List.of();
    return StreamSupport.stream(entities.spliterator(), false).map(this::toModel).collect(toList());
  }

}
