package com.jra.sampleecommerce.hateoas;

import com.jra.sampleecommerce.api.model.UserDTO;
import com.jra.sampleecommerce.controller.CustomerController;
import com.jra.sampleecommerce.model.entity.User;
import org.springframework.beans.BeanUtils;
import org.springframework.hateoas.server.mvc.RepresentationModelAssemblerSupport;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Objects;
import java.util.stream.StreamSupport;

import static java.util.stream.Collectors.toList;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;

@Component
public class UserRepresentationModelAssembler extends
        RepresentationModelAssemblerSupport<User, UserDTO> {

    /**
     * Creates a new {@link RepresentationModelAssemblerSupport} using the given controller class and
     * resource type.
     */
    public UserRepresentationModelAssembler() {
        super(CustomerController.class, UserDTO.class);
    }

    /**
     * Coverts the User entity to resource
     *
     * @param entity
     */
    @Override
    public UserDTO toModel(User entity) {
        UserDTO resource = createModelWithId(entity.getId(), entity);
        BeanUtils.copyProperties(entity, resource);
        resource.setId(entity.getId().toString());
        // Self link generated by createModelWithId has missing api path. Therefore, generating additionally.
        // can be removed once fixed.
        resource.add(
                linkTo(methodOn(CustomerController.class).getCustomerById(entity.getId().toString()))
                        .withSelfRel());
        resource.add(
                linkTo(methodOn(CustomerController.class).getAllCustomers()).withRel("customers"));
        resource
                .add(
                        linkTo(methodOn(CustomerController.class)
                                .getAddressesByCustomerId(entity.getId().toString())).withRel("self_addresses"));
        return resource;
    }

    /**
     * Coverts the collection of Product entities to list of resources.
     *
     * @param entities
     */
    public List<UserDTO> toListModel(Iterable<User> entities) {
        if (Objects.isNull(entities)) {
            return List.of();
        }
        return StreamSupport.stream(entities.spliterator(), false).map(this::toModel)
                .collect(toList());
    }

}
